# Generated by Django 3.0.5 on 2021-01-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_team_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='numTeams',
        ),
    ]
