# Generated by Django 3.0.5 on 2021-01-25 21:04

from django.db import migrations
import djongo.models.fields
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210121_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=djongo.models.fields.ArrayField(default=1, model_container=main_app.models.Team, model_form_class=main_app.models.TeamForm),
            preserve_default=False,
        ),
    ]
