# Generated by Django 3.0.5 on 2021-01-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_tournament_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
