# Generated by Django 3.0.5 on 2021-01-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210126_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
